import pandas as pd
import matplotlib.pyplot as plt
import ast  # To safely evaluate the string representation of the lists
import numpy as np
import matplotlib.animation as animation
import matplotlib.patches as patches

def read_positions_from_csv(filename):
    """Read particle positions from CSV with the format: step,[[x1,y1,z1], [x2,y2,z2],...]"""
    data = []
    times = []
    
    # Read the CSV file
    with open(filename, 'r') as file:
        for line in file:
            time, positions_str = line.strip().split(',', 1)
            times.append(float(time))  # Store the time step
            positions = ast.literal_eval(positions_str)  # Convert string list to actual list
            # Store positions for each step
            data.append(positions)
    
    return data, times

def main():
    # Filepath to the CSV file generated by C++ code
    filename = 'positions.csv'
    
    # Read particle positions from the CSV
    data, times = read_positions_from_csv(filename)

    data_array = np.array(data)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # Set limits based on the data
    all_positions = data_array.reshape(-1, 3)
    vmax = max(max(max(abs(all_positions[:, 0].min()), all_positions[:, 0].max()), max(abs(all_positions[:, 1].min()), all_positions[:, 1].max())), max(abs(all_positions[:, 2].min()), all_positions[:, 2].max()))
    xlim = (-vmax, vmax)
    ylim = (-vmax, vmax)
    zlim = (-vmax, vmax)

    scat = ax.scatter([], [], [], s=5, color="red")

    earthRadius = 6378000.0

    u = np.linspace(0, 2 * np.pi, 100)
    v = np.linspace(0, np.pi, 100)
    x = earthRadius * np.outer(np.cos(u), np.sin(v))
    y = earthRadius * np.outer(np.sin(u), np.sin(v))
    z = earthRadius * np.outer(np.ones(np.size(u)), np.cos(v))


    def init():
        ax.set_xlim(xlim)
        ax.set_ylim(ylim)
        ax.set_zlim(zlim)
        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_zlabel('Z')
        ax.plot_surface(x, y, z, color='b', alpha=0.5)
        ax.set_aspect('equal', adjustable='box')
        return scat,

    def update(frame):
        positions = data_array[frame]
        time = times[frame]
        scat._offsets3d = (positions[:, 0], positions[:, 1], positions[:, 2], )
        ax.set_title(f"Time (s): {time}")
        return scat,

    ani = animation.FuncAnimation(fig, update, frames=len(data_array), interval=1, init_func=init, blit=False)

    plt.show()
        
if __name__ == "__main__":
    main()